### ISSUE TITLE
stop propagation

### ISSUE THREAD

**Issue by cgbrucezjy** [sprmn/react-firebase-file-uploader#8]
I'm not sure if it's common request, but in my code, this element is child of another clickable component, so I added this to stop propagation.

```
				_react2.default.createElement('input', {
					name: name,
					type: 'file',
					accept: 'image/*',
					onChange: this.handleImageSelection,
					onClick: (e)=>{e.stopPropagation()}
				})
```

**Comment by sprmn** [comment]
Hey @cgbrucezjy thanks for sharing, I added this to the docs of the next release. 👍
